""" add difficulty_level column

Revision ID: 508deb99900a
Revises: bb5826a0c39a
Create Date: 2026-06-13 20:59:43.788771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508deb99900a'
down_revision = 'bb5826a0c39a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobbies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty_level', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobbies', schema=None) as batch_op:
        batch_op.drop_column('difficulty_level')

    # ### end Alembic commands ###
